### ISSUE TITLE
(UndefinedFunctionError) function :asn1ct.compile/2 is undefined (

### ISSUE THREAD

**Issue by dfalling** [tanguilp/wax#3]
Hiya, thanks a lot for this library!  I've gotten Wax working locally, but when I try to deploy to my server I'm having issues with asn1ct.  I see the calls to it in `priv/android_key/AndroidKeyAttestationV1` but it doesn't seem to be a dependency.  Have you see these issues?

Cheers!

<details>
<summary>Full crash log</summary>

```
2019-03-08T21:26:09.974426+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  | 21:26:09.973 [info] Application wax exited: exited in: Wax.Application.start(:normal, [])
2019-03-08T21:26:09.974439+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |     ** (EXIT) an exception was raised:
2019-03-08T21:26:09.974465+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |             :asn1ct.compile('/app/lib/wax-0.1.1/priv/android_key/AndroidKeyAttestationV1.asn1', [outdir: '/app/lib/wax-0.1.1/priv/android_key/asn_generated'])
2019-03-08T21:26:09.974440+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |         ** (UndefinedFunctionError) function :asn1ct.compile/2 is undefined (module :asn1ct is not available)
2019-03-08T21:26:09.974499+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |             (wax) lib/wax/attestation_statement_format/android_key.ex:347: Wax.AttestationStatementFormat.AndroidKey.install_asn1_module/0
2019-03-08T21:26:09.974622+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |             (kernel) application_master.erl:273: :application_master.start_it_old/4
2019-03-08T21:26:09.974621+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |             (wax) lib/wax/application.ex:8: Wax.Application.start/2
2019-03-08T21:26:11.575074+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  | {"Kernel pid terminated",application_controller,"{application_start_failure,wax,{bad_return,{{'Elixir.Wax.Application',start,[normal,[]]},{'EXIT',{undef,[{asn1ct,compile,[\"/app/lib/wax-0.1.1/priv/android_key/AndroidKeyAttestationV1.asn1\",[{outdir,\"/app/lib/wax-0.1.1/priv/android_key/asn_generated\"}]],[]},{'Elixir.Wax.AttestationStatementFormat.AndroidKey',install_asn1_module,0,[{file,\"lib/wax/attestation_statement_format/android_key.ex\"},{line,347}]},{'Elixir.Wax.Application',start,2,[{file,\"lib/wax/application.ex\"},{line,8}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
2019-03-08T21:26:11.579166+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  |
2019-03-08T21:26:11.575092+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  | Kernel pid terminated (application_controller) ({application_start_failure,wax,{bad_return,{{'Elixir.Wax.Application',start,[normal,[]]},{'EXIT',{undef,[{asn1ct,compile,["/app/lib/wax-0.1.1/priv/andro
2019-03-08T21:26:13.596870+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  | Crash dump is being written to: erl_crash.dump...done
2019-03-08T21:26:14.473527+00:00 ido-api[ido-api-2963338555-8gsv1]: web.1  | exited with code 1
```
</details>

**Comment by tanguilp** [comment]
Hi, thanks for the report. I'll check tomorrow evening. Cheers

**Comment by tanguilp** [comment]
How do you deploy your app? Using an Erlang release file?

**Comment by dfalling** [comment]
I use [distillery](https://github.com/bitwalker/distillery/).

**Comment by dfalling** [comment]
Here are the workarounds I've tried without luck:
- add `:asn1` to my `extra_applications` (from a [similar ticket](https://github.com/bitwalker/distillery/issues/627))
- add [asn1ex](https://github.com/vicentfg/asn1ex) as a dependency (wild shot in the dark here).
- fork this repo and simply disable the compilation line, since I'm not using the Android key feature.
`# Wax.AttestationStatementFormat.AndroidKey.install_asn1_module()`  This didn't work as other components seem to be dependent on this even if the Android functions aren't called.
- fork this repo and add `:asn1` to its `extra_applications`

**Comment by tanguilp** [comment]
Thanks for the comments. The ASN1 files are compiled at runtime. It seems that the asn1 functions are not available when using releases (not sure why).

Can you try the  asn_gen_at_compile_time branch (commit 0638fb7318f373b7cb7b3bc1eed8dad4aebe2aee) instead? It compiles ASN1 files at compile time (sic) which makes more sense anyway. I have unfortunately no experience with releases, so I'm not sure if it'll use the mix.exs file. Please tell me if that's ok, so that I merge it with the trunk.

Cheers

**Comment by dfalling** [comment]
Hey, thanks for the support!  Watching my builds on prod I can see that the Android files are successfully compiled now.  Sadly I have another issue and the logs are pretty worthless:
```
2019-03-12T20:00:08.017763+00:00 ido-api[ido-api-2032071908-8hxc7]: web.1  | 20:00:08.017 [info] Application wax exited: shutdown
2019-03-12T20:00:09.573674+00:00 ido-api[ido-api-2032071908-8hxc7]: web.1  | {"Kernel pid terminated",application_controller,"{application_terminated,wax,shutdown}"}
2019-03-12T20:00:09.573687+00:00 ido-api[ido-api-2032071908-8hxc7]: web.1  | Kernel pid terminated (application_controller) ({application_terminated,wax,shutdown})
```

It only happens on my server (hosted on gigalixir) which doesn't cache the `erl_crash.dump` file when the server crashes and restarts.  I bugged theme earlier and they suggested I troubleshoot locally (which sadly hasn't helped), so I'll reach out again and see if there are any other things I can do to track this down.

**Comment by tanguilp** [comment]
Hmm thanks for the report. The only "live" part of the Wax application is the metadata update process, so I'm thinking it might be faulty here. I've tried incorrect token, no networking, etc. but it fails gracefully (just emitting a warning).
Maybe you could try setting an invalid token? It'll for sure fail without crashing the app.

**Comment by dfalling** [comment]
I tried an invalid token and am having the same problem.  I don't see any of Wax's metadata / startup logs- just the messages about it terminating.

**Comment by tanguilp** [comment]
If you don't see the logger info "Starting FIDO metadata update process" message and should (is your log level high enough?), then the only thing that could fail before in lib/metadata.ex is the ets table creation. Are you sure there's no restriction on that?

**Comment by dfalling** [comment]
In my fork of this repo I added a ton of logging to troubleshoot.  So far I don't see any functions that failing, but only two functions seem to be called...  metadata::init, and metadata::start_link.  One odd thing is they seem to both be called multiple times before the application ultimately dies.

<details>
<summary>Logs</summary>

```
2019-03-12T22:55:06.575520+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] Starting wax
2019-03-12T22:55:06.575933+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting supervisor
2019-03-12T22:55:06.575934+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (1)
2019-03-12T22:55:06.575934+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (1)
2019-03-12T22:55:06.575935+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (2)
2019-03-12T22:55:06.576034+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init result {:ok, [serial_number: 0], {:continue, :update_metadata}}
2019-03-12T22:55:06.576915+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (2)
2019-03-12T22:55:06.576916+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link result {:ok, #PID<0.2046.0>}
2019-03-12T22:55:06.576916+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (1)
2019-03-12T22:55:06.576917+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (1)
2019-03-12T22:55:06.576937+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (2)
2019-03-12T22:55:06.576943+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init result {:ok, [serial_number: 0], {:continue, :update_metadata}}
2019-03-12T22:55:06.576943+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (2)
2019-03-12T22:55:06.576944+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link result {:ok, #PID<0.2047.0>}
2019-03-12T22:55:06.576944+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (1)
2019-03-12T22:55:06.576951+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (1)
2019-03-12T22:55:06.576951+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (2)
2019-03-12T22:55:06.576952+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init result {:ok, [serial_number: 0], {:continue, :update_metadata}}
2019-03-12T22:55:06.576952+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (2)
2019-03-12T22:55:06.577324+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link result {:ok, #PID<0.2048.0>}
2019-03-12T22:55:06.577339+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (1)
2019-03-12T22:55:06.577344+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (1)
2019-03-12T22:55:06.577344+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init (2)
2019-03-12T22:55:06.577345+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX init result {:ok, [serial_number: 0], {:continue, :update_metadata}}
2019-03-12T22:55:06.577345+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link (2)
2019-03-12T22:55:06.577351+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [debug] WAX Starting link result {:ok, #PID<0.2050.0>}
2019-03-12T22:55:06.577518+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | [info] Application wax exited: shutdown
2019-03-12T22:55:08.174376+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | {"Kernel pid terminated",application_controller,"{application_terminated,wax,shutdown}"}
2019-03-12T22:55:08.174397+00:00 ido-api[ido-api-2804872216-4fbcm]: web.1  | Kernel pid terminated (application_controller) ({application_terminated,wax,shutdown})
```
</details>

**Comment by tanguilp** [comment]
Ok so according to your log init properly executes but handle_continue is not (https://github.com/dfalling/wax/blob/asn_gen_at_compile_time/lib/wax/metadata.ex#L91 is not printed).

Handle_continue is an OTP21+ thing (https://hexdocs.pm/elixir/GenServer.html#c:handle_continue/2), which version of OTP are you running?

**Comment by dfalling** [comment]
Good catch- I had that hunch last night too but forgot to post here.  I'm having an issue pushing a new build currently, but once I get that deployed I'll report back.  I think that has to be it- I have logging everywhere else and nothing seems off.  Thanks!

**Comment by dfalling** [comment]
Yep, that was it!  I had upgraded my Elixir version and didn't realize that wouldn't upgrade Erlang/OTP as well.  I confirmed this is working great in prod.  Thanks!

**Comment by tanguilp** [comment]
Great news, thanks for your help!
I'll merge the branch and add a compatibility notice today or tomorrow.
